# -*- coding: utf-8 -*-
"""Doc-Genie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djvB6V7B5KrZuoW2jMhRWhrYZZz-nwNf
"""

# --- Bring requests up to what google-adk wants (>=2.32.4,<3)
!pip -q install "requests>=2.32.4,<3"

# --- (Optional) Reassert the rest of your modern stack in case the runtime changed anything
!pip -q install "gradio==5.50.0" "websockets>=15,<17" "uvicorn==0.41.0" "reportlab==4.0.7" "black==24.1.1" "autopep8==2.1.0"

# ===== Doc-Genie: Professional Python Function Docstring Generator with AST Analysis =====
# Implements: AST-based function parsing, logic analysis, Google/NumPy docstrings,
# Gradio UI with code editor + file upload, PDF/TXT export, simple history, share links.

import ast
import io
import os
import json
import textwrap
import tempfile
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import quote

import gradio as gr
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, Table, TableStyle

# ----------------------------
# Helpers
# ----------------------------
def _unparse(node: ast.AST) -> str:
    """Return Python source for an AST node (requires Python 3.9+)."""
    try:
        return ast.unparse(node)
    except Exception:
        return repr(node)

def _annotation_to_text(ann) -> Optional[str]:
    if ann is None:
        return None
    try:
        return _unparse(ann)
    except Exception:
        return None

def _default_to_text(node) -> Optional[str]:
    if node is None:
        return None
    try:
        return _unparse(node)
    except Exception:
        return None

def _guess_literal_type(node: ast.AST) -> Optional[str]:
    if isinstance(node, ast.Constant):
        if isinstance(node.value, bool):
            return "bool"
        if isinstance(node.value, int):
            return "int"
        if isinstance(node.value, float):
            return "float"
        if isinstance(node.value, str):
            return "str"
        if node.value is None:
            return "None"
    if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return "Sequence"
    if isinstance(node, ast.Dict):
        return "dict"
    return None

def _union_type_str(types: List[str]) -> str:
    uniq = sorted({t for t in types if t})
    if not uniq:
        return "Any"
    if len(uniq) == 1:
        return uniq[0]
    return f"Union[{', '.join(uniq)}]"

# ----------------------------
# Core Analyzer
# ----------------------------
class DocGenieAnalyzer:
    """
    Core AST-based analyzer that extracts function signatures and performs
    lightweight logic analysis to inform docstring generation.
    """

    @staticmethod
    def parse_functions(code: str) -> List[ast.AST]:
        tree = ast.parse(code)
        return [n for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]

    @staticmethod
    def extract_function_signature(func_def: ast.AST) -> Dict[str, Any]:
        args = func_def.args
        params: List[Dict[str, Any]] = []

        posonly = getattr(args, "posonlyargs", [])
        all_positional = list(posonly) + list(args.args)
        defaults = [None] * (len(all_positional) - len(args.defaults)) + list(args.defaults)

        for arg, default in zip(all_positional, defaults):
            params.append({
                "name": arg.arg,
                "type": _annotation_to_text(arg.annotation) or "Any",
                "default": _default_to_text(default)
            })

        if args.vararg:
            params.append({
                "name": f"*{args.vararg.arg}",
                "type": _annotation_to_text(args.vararg.annotation) or "Any",
                "default": None
            })

        for kw, default in zip(args.kwonlyargs, args.kw_defaults):
            params.append({
                "name": kw.arg,
                "type": _annotation_to_text(kw.annotation) or "Any",
                "default": _default_to_text(default)
            })

        if args.kwarg:
            params.append({
                "name": f"**{args.kwarg.arg}",
                "type": _annotation_to_text(args.kwarg.annotation) or "Any",
                "default": None
            })

        return_type = _annotation_to_text(func_def.returns) or "Any"
        return {
            "name": func_def.name,
            "params": params,
            "return_type": return_type,
            "is_async": isinstance(func_def, ast.AsyncFunctionDef),
            "decorators": [_unparse(d) for d in getattr(func_def, "decorator_list", [])],
        }

    @staticmethod
    def analyze_function_logic(func_def: ast.AST) -> Dict[str, Any]:
        ops_map = {
            ast.Add: "addition",
            ast.Sub: "subtraction",
            ast.Mult: "multiplication",
            ast.Div: "division",
            ast.FloorDiv: "floor_division",
            ast.Mod: "modulo",
            ast.Pow: "power",
            ast.MatMult: "matrix_multiplication",
        }

        has_loops = False
        has_conditions = False
        operations: List[str] = []
        function_calls: List[str] = []
        variables: List[str] = []
        returns_types: List[str] = []

        class V(ast.NodeVisitor):
            def visit_For(self, node):
                nonlocal has_loops
                has_loops = True
                self.generic_visit(node)
            def visit_While(self, node):
                nonlocal has_loops
                has_loops = True
                self.generic_visit(node)
            def visit_If(self, node):
                nonlocal has_conditions
                has_conditions = True
                self.generic_visit(node)
            def visit_BinOp(self, node):
                op_type = ops_map.get(type(node.op))
                if op_type:
                    operations.append(op_type)
                self.generic_visit(node)
            def visit_Call(self, node):
                name = None
                if isinstance(node.func, ast.Name):
                    name = node.func.id
                elif isinstance(node.func, ast.Attribute):
                    name = f"{_unparse(node.func.value)}.{node.func.attr}"
                if name:
                    function_calls.append(name)
                self.generic_visit(node)
            def visit_Name(self, node):
                variables.append(node.id)
                self.generic_visit(node)
            def visit_Return(self, node):
                if node.value is None:
                    returns_types.append("None")
                else:
                    guess = _guess_literal_type(node.value)
                    returns_types.append(guess or "Unknown")
                self.generic_visit(node)

        V().visit(func_def)
        operations = sorted(set(operations))
        function_calls = sorted(set(function_calls))
        variables = sorted(set(variables))
        returns_types = sorted(set([t for t in returns_types if t]))

        desc_parts = []
        if has_loops:
            desc_parts.append("iterative processing")
        if has_conditions:
            desc_parts.append("conditional logic")
        if operations:
            desc_parts.append("mathematical operations: " + ", ".join(operations))
        if function_calls:
            desc_parts.append("calls: " + ", ".join(function_calls))
        description = "Executes " + (", ".join(desc_parts) if desc_parts else "core computation") + "."

        return {
            "has_loops": has_loops,
            "has_conditions": has_conditions,
            "operations": operations,
            "function_calls": function_calls,
            "variables": variables,
            "returns_types": returns_types or ["Unknown"],
            "description": description
        }

    @staticmethod
    def generate_google_docstring(signature: Dict[str, Any], analysis: Dict[str, Any]) -> str:
        name = signature["name"]
        summary = f"{name}.\n\n{analysis['description']}"
        args_lines = []
        for p in signature["params"]:
            pname = p["name"]
            ptype = p["type"] or "Any"
            if pname.startswith("*"):
                pname_disp = pname
            else:
                pname_disp = f"{pname} ({ptype})"
            args_lines.append(f"    {pname_disp}: Parameter `{pname}`.")
        returns = _union_type_str([signature["return_type"]] + analysis.get("returns_types", []))
        ds = '"""' + f"\n{summary}\n\n"
        if args_lines:
            ds += "Args:\n" + "\n".join(args_lines) + "\n\n"
        ds += f"Returns:\n    {returns}: Function result.\n" + '"""'
        return ds

    @staticmethod
    def generate_numpy_docstring(signature: Dict[str, Any], analysis: Dict[str, Any]) -> str:
        name = signature["name"]
        summary = f"{name}.\n\n{analysis['description']}"
        params_lines = []
        for p in signature["params"]:
            pname = p["name"]
            ptype = p["type"] or "Any"
            params_lines.append(f"{pname} : {ptype}\n    Parameter `{pname}`.")
        returns = _union_type_str([signature["return_type"]] + analysis.get("returns_types", []))
        ds = '"""' + f"\n{summary}\n\n"
        if params_lines:
            ds += "Parameters\n----------\n" + "\n".join(params_lines) + "\n\n"
        ds += "Returns\n-------\n" + f"{returns}\n    Function result.\n" + '"""'
        return ds

    @staticmethod
    def inject_docstrings(code: str, style: str = "google") -> Tuple[str, List[Dict[str, Any]]]:
        tree = ast.parse(code)
        updates: List[Dict[str, Any]] = []

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue

            sig = DocGenieAnalyzer.extract_function_signature(node)
            analysis = DocGenieAnalyzer.analyze_function_logic(node)
            if style.lower() == "numpy":
                docstring = DocGenieAnalyzer.generate_numpy_docstring(sig, analysis)
            else:
                docstring = DocGenieAnalyzer.generate_google_docstring(sig, analysis)

            if node.body and isinstance(node.body[0], ast.Expr) and isinstance(getattr(node.body[0], "value", None), ast.Constant) and isinstance(node.body[0].value.value, str):
                node.body[0].value.value = docstring
                action = "replaced"
            else:
                doc_node = ast.Expr(value=ast.Constant(value=docstring))
                node.body.insert(0, doc_node)
                action = "inserted"

            updates.append({
                "function": sig["name"],
                "action": action,
                "style": style.lower(),
                "analysis": analysis,
                "signature": sig
            })

        ast.fix_missing_locations(tree)
        updated = _unparse(tree)
        return updated, updates

# ----------------------------
# Exporters
# ----------------------------
def export_to_pdf(updated_code: str, updates: List[Dict[str, Any]]) -> str:
    fd, path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)
    doc = SimpleDocTemplate(path, pagesize=A4)
    story = []

    title_style = ParagraphStyle(name="Title", fontName="Helvetica-Bold", fontSize=16, spaceAfter=12, alignment=TA_LEFT)
    header_style = ParagraphStyle(name="Header", fontName="Helvetica-Bold", fontSize=12, spaceAfter=8)
    body_style = ParagraphStyle(name="Body", fontName="Helvetica", fontSize=10, leading=13)

    story.append(Paragraph("Doc-Genie — Automated Docstring Report", title_style))
    story.append(Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M:%S"), body_style))
    story.append(Spacer(1, 10))

    data = [["Function", "Action", "Style", "Loops", "Conds", "Ops", "Calls"]]
    for u in updates:
        a = u["analysis"]
        data.append([
            u["function"],
            u["action"],
            u["style"],
            "✓" if a["has_loops"] else "—",
            "✓" if a["has_conditions"] else "—",
            ", ".join(a["operations"]) or "—",
            ", ".join(a["function_calls"]) or "—",
        ])
    table = Table(data, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
    ]))
    story.append(table)
    story.append(Spacer(1, 12))
    story.append(Paragraph("Updated Code", header_style))
    story.append(Spacer(1, 4))
    story.append(Preformatted(updated_code, style=body_style))
    doc.build(story)
    return path

def export_to_txt(updated_code: str, updates: List[Dict[str, Any]]) -> str:
    fd, path = tempfile.mkstemp(suffix=".txt")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("# Doc-Genie — Documentation Export\n")
        f.write(datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n\n")
        f.write("## Summary\n")
        for u in updates:
            a = u["analysis"]
            f.write(f"- {u['function']} [{u['action']}, style={u['style']}]; loops={a['has_loops']}; conds={a['has_conditions']}; ops={','.join(a['operations']) or '-'}; calls={','.join(a['function_calls']) or '-'}\n")
        f.write("\n## Updated Code\n\n")
        f.write(updated_code)
    return path

# ----------------------------
# Gradio Interface
# ----------------------------
EXAMPLE_CODE = textwrap.dedent('''\
def calculate(x: int, y: float = 3.5) -> float:
    if x > 0:
        total = 0
        for i in range(x):
            total += i * y
        return total
    return y

def greet(name):
    return "Hello " + str(name)
''')

with gr.Blocks(title="Doc-Genie — AST Docstring Generator") as demo:
    gr.Markdown("## Doc-Genie — Professional Python Function Docstring Generator\n"
                "Paste code or upload a `.py` file, choose a docstring style, and generate. "
                "Then export to PDF/TXT or share.")
    with gr.Row():
        with gr.Column(scale=3):
            code_in = gr.Code(label="Python code input (.py)", value=EXAMPLE_CODE, language="python", lines=20)
            file_in = gr.File(label="Upload a .py file (optional)", file_types=[".py"])
            style = gr.Radio(["google", "numpy"], value="google", label="Docstring style")
            generate_btn = gr.Button("Generate Docstrings", variant="primary")
        with gr.Column(scale=2):
            updated_code = gr.Code(label="Code with generated docstrings", language="python", lines=20)
            analysis_json = gr.JSON(label="Analysis summary (per function)")
            with gr.Row():
                pdf_btn = gr.Button("Export PDF")
                txt_btn = gr.Button("Export TXT")
            pdf_out = gr.File(label="PDF file")
            txt_out = gr.File(label="TXT file")
            share_md = gr.Markdown()

    history_state = gr.State([])

    def _read_input(code_text, file_obj):
        # Gradio 4.x file payloads vary: could be path string, dict with 'path', or file object.
        if file_obj:
            try:
                # If dict-like with a 'path' key
                if isinstance(file_obj, dict) and "path" in file_obj:
                    path = file_obj["path"]
                # If it's a list (multi-file), take the first
                elif isinstance(file_obj, list) and file_obj:
                    first = file_obj[0]
                    if isinstance(first, dict) and "path" in first:
                        path = first["path"]
                    else:
                        path = getattr(first, "name", str(first))
                else:
                    path = getattr(file_obj, "name", str(file_obj))
                with open(path, "r", encoding="utf-8") as fh:
                    return fh.read()
            except Exception:
                pass
        return code_text or ""

    def do_generate(code_text, file_obj, style_sel, history):
        code = _read_input(code_text, file_obj).replace("\r\n", "\n")
        if not code.strip():
            return gr.update(), gr.update(), history, gr.update(value="> Please provide Python code.")
        updated, updates = DocGenieAnalyzer.inject_docstrings(code, style_sel)
        ts = datetime.now().isoformat(timespec="seconds")
        history = (history or []) + [{"timestamp": ts, "updates": updates}]
        msg = f"Doc-Genie generated docstrings for {len(updates)} function(s) at {ts}."
        wa = f"https://api.whatsapp.com/send?text={quote(msg)}"
        fb = f"https://www.facebook.com/sharer/sharer.php?u=&quote={quote(msg)}"
        share_block = f"**Share:** [WhatsApp]({wa}) · [Facebook]({fb})"
        return updated, updates, history, gr.update(value=share_block)

    def do_pdf(updated, updates):
        if not updated:
            return None
        path = export_to_pdf(updated, updates or [])
        return path

    def do_txt(updated, updates):
        if not updated:
            return None
        path = export_to_txt(updated, updates or [])
        return path

    generate_btn.click(
        do_generate,
        inputs=[code_in, file_in, style, history_state],
        outputs=[updated_code, analysis_json, history_state, share_md]
    )
    pdf_btn.click(do_pdf, inputs=[updated_code, analysis_json], outputs=[pdf_out])
    txt_btn.click(do_txt, inputs=[updated_code, analysis_json], outputs=[txt_out])

demo.launch(share=True)